#!/usr/bin/env php
<?php

$loader = require_once __DIR__ . '/vendor/autoload.php';
$loader->addPsr4('Spear\\Silex\\Application\\', __DIR__ . '/../spear-application/src/');

use Puzzle\Configuration\Yaml;
use Puzzle\Configuration\Stacked;
use Gaufrette\Filesystem;
use Gaufrette\Adapter\Local;
use Supervisorg\Application;
use Supervisorg\Console;

$configurationFilesStorage = new Filesystem(new Local(__DIR__ . '/config/built-in'));
$configurationBuiltIn = new Yaml($configurationFilesStorage);

$configurationFilesStorage = new Filesystem(new Local(__DIR__ . '/config/local'));
$configurationLocal = new Yaml($configurationFilesStorage);

$configuration = new Stacked();
$configuration->overrideBy($configurationBuiltIn)
    ->overrideBy($configurationLocal);

$rootDir = realpath(__DIR__);

$app = new Application($configuration, $rootDir);

$console = new Console\Console($app);
$console->run();
