#!/usr/bin/env php
<?php

$loader = require_once __DIR__ . '/vendor/autoload.php';
$loader->addPsr4('Spear\\Silex\\Application\\', __DIR__ . '/../spear-application/src/');

use Puzzle\Configuration\Yaml;
use Gaufrette\Filesystem;
use Gaufrette\Adapter\Local;
use Supervisorg\Application;
use Supervisorg\Console;

$configurationFilesStorage = new Filesystem(new Local(__DIR__ . '/config'));
$configuration = new Yaml($configurationFilesStorage);
$rootDir = realpath(__DIR__);

$app = new Application($configuration, $rootDir);

$console = new Console\Console($app);
$console->run();